# Generated by Django 4.2.16 on 2024-11-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.CharField(default="example@email.com", max_length=100),
        ),
    ]
