# Generated by Django 4.2.16 on 2024-11-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regi", "0002_person_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hobbies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("hobbies", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("marks", models.CharField(max_length=250)),
            ],
        ),
    ]
