# Generated by Django 4.2.16 on 2024-11-07 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regi", "0003_hobbies_marks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=250)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
